# Conclusión
La biogeografía estudia la distribución de la vida en el espacio y tiempo. Un tema frecuente dentro de esta disciplina han sido los patrones de la diversidad biológica, así como los factores bióticos y abióticos que la determinan (Whittaker et al., 2005; Lomolino, Riddle y Whittaker, 2017). Una forma en la que se ha estudiado es a través de medidas que cuantifican alguna característica de la biodiversidad, como es el caso de la riqueza, el endemismo ponderado y la diversidad filogenética. 

Estas métricas pueden ser de utilidad en la conservación, ya que permiten establecer criterios de priorización de áreas y generar enfoques complementarios que permitan preservar elementos que no se suelen tomar en cuenta en las áreas naturales protegidas actuales (Winter et al., 2012). Ejemplo de ello es la aplicación de la diversidad filogenética en la planeación de estas áreas, la cual permite conocer la historia evolutiva de una extensión dada y comparar o cuantificar esa historia entre áreas (Miller et al., 2018). Esto permite conservar linajes distintos, cada uno con una importancia ecológica y evolutiva única. 

Asimismo, comprender en qué grado los factores abióticos influyen en los patrones de biodiversidad permite entender los procesos históricos y biológicos que los han moldeado. Es el caso de la heterogeneidad ambiental, como la que ocurre en las zonas de transición entre distintos hábitats, que se suele asociar a una mayor riqueza de especies en comparación con regiones que presentan menor variación geográfica o climática (Lomolino, Riddle y Whittaker, 2017). Por tanto, cuantificar la influencia de esta heterogeneidad sobre los patrones de diversidad resulta fundamental tanto para revelar los mecanismos que han dado origen a la biodiversidad, así como para definir prioridades de conservación.

Uno de los géneros de árboles de gran importancia ecológica en el país son los encinos. Representan el grupo con mayor biomasa y diversidad entre los árboles de los bosques mexicanos. Además de su importancia evolutiva, estos organismos desempeñan un papel clave al proveer hábitat, alimento y múltiples servicios ecosistémicos (Cavender-Bares, 2018). 
No obstante, el género Quercus se encuentra en situación de riesgo, los bosques de encinos representan uno de los ecosistemas con mayores pérdidas, donde el 20% de las especies del país se encuentran amenazadas de extinción (Good et al., 2024). 
Por ello, resulta relevante evaluar los patrones de riqueza, endemismo y diversidad filogenética de los encinos en México, así como analizar el papel que desempeñan la heterogeneidad topográfica y climática en su configuración. Este análisis permitiría identificar patrones biogeográficos del género y contribuir a llenar vacíos en materia de conservación, especialmente en lo referente a la distribución y concentración de distintas dimensiones de la biodiversidad. Asimismo, es prioritario determinar qué proporción de estos valores de biodiversidad se encuentra actualmente bajo protección dentro del sistema de Áreas Naturales Protegidas (ANP), con el propósito de detectar vacíos de conservación y proponer estrategias complementarias basadas en métricas integradas de biodiversidad.
Para ello, se consideran las siguientes preguntas de investigación:
 i) ¿Cuál es el efecto de la heterogeneidad topográfica y climática sobre los patrones de riqueza, endemismo y diversidad filogenética de los encinos en México?
 ii) ¿Qué proporción de estos valores se encuentra dentro de las ANP actuales?

