project:
  type: book

book:
  title: "titulo"
  author: "Gabriela Centeno Cabada"
  date: "4/8/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - metodologia.qmd
    - resultados.qmd
    - discusion.qmd
    - conclusion.qmd

bibliography:   
  - references.bib
  - zotero.bib
  
citation-style: apa

crossref:
  fig-prefix: "Figura"

format:
  pdf:
    number-sections: true
    number-depth: 2
    fig-caption: true
    eqn-number: true
  html:
    number-sections: true
    number-depth: 2
    fig-caption: true
    eqn-number: true

editor: visual
