---
title: "metodologia"
format: html
---

##Datos espaciales De donde sacamos los datos (DOI de descarga y filtros) y programas (versiones) Como se limpiaron Filtros Corrección taxonómica (backbone gbif) Cómo completamos la información de estatus de conservación (IUCN) paquetes utilizados Criterios de aceptación de especies Cuantas especies quedaron y total de registros (puedes hacer la tabla) Insumos geográficos Capa de provincias biogeográficas Capa de estados/municipios Extracción de elevación

##Evaluación de sesgo de muestreo/escala Escalas consideradas ¿Qué tanto se representa la heterogeneidad de una provincia biogeografica? \*graficas de cuadros por región Curvas de rarefacción (cuadros vs riqueza) Relación \# registros vs riqueza

##Árbol filogenético De donde sacamos los datos TOL (tree of life) Hipp 2020? Paquete para recortar el árbol

##Índices de biodiversidad (Diversity metrics) Cómo usamos phyloraster (ver que se reporta normalmente) CANAPE (PENDIENTE) Regression models? (PENDIENTE)
